version: "3.9"

services:

  tirios:
    image: tirios
    container_name: tirios
    ports:
      - "3099:3099"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: bestcity
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
