version: "3.9"

services:

  tirios:
    build: .
    command: npm run server
    environment:
      NODE_ENV: development
    ports:
      - "3099:3099"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    ports:
      - "27018:27017"
